name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: <owner>/github-actions-hands-on@main
      - uses: <owner>/github-actions-hands-on/actions/bye@main
